name: MoneyHacks
favicon: null
layout_spectrum: 0.2788127639796585
typography_spectrum: 0.6803158645052463
title: Make money online
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#0252b3'
    - '#0089fe'
    - '#97fdff'
    - '#44b1f3'
  brandStrength: 0.5625
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
